[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "libglvnd", "ffmpeg"]

[phases.install]
cmds = [
  "python3.12 -m pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]
